baseURL = 'https://v01dsider.github.io/'
languageCode = 'es-mx'
title = 'La Guarida'
theme = "not-much"

[params]
	subtitle = 'Blog de Luis Valencia'

# For LaTeX support
[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
